sudo: false
language: node_js
node_js:
  - "7"
  - "6"
  - "4.3"
script: npm run travis
env:
  - NO_WATCH_TESTS=1

before_script:
  - npm link
  - npm link webpack

after_success:
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - cat ./coverage/coverage.json | node_modules/codecov.io/bin/codecov.io.js
  - rm -rf ./coverage
