# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

branches:
  only:
    - master

init:
  - git config --global core.autocrlf input

# what combinations to test
environment:
  matrix:
    - nodejs_version: 7
      job_part: test
    - nodejs_version: 6
      job_part: test

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install --msvs_version=2013
  - npm link
  - npm link webpack

build: off

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - cmd: npm run appveyor:%job_part%
